-- MySQL Script generated by MySQL Workbench
-- 03/22/16 19:03:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema parque
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parque` ;

-- -----------------------------------------------------
-- Schema parque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parque` DEFAULT CHARACTER SET utf8 ;
USE `parque` ;

-- -----------------------------------------------------
-- Table `parque`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Especie` (
  `id_especie` INT NOT NULL AUTO_INCREMENT,
  `nombre_cientifico` VARCHAR(45) NOT NULL,
  `nombre_comun` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(100) NULL,
  PRIMARY KEY (`id_especie`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_especie_UNIQUE` ON `parque`.`Especie` (`id_especie` ASC);


-- -----------------------------------------------------
-- Table `parque`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nombre_area` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idArea_UNIQUE` ON `parque`.`Area` (`id_area` ASC);


-- -----------------------------------------------------
-- Table `parque`.`Especie_Areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Especie_Areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especies_idEspecie` INT NOT NULL,
  `areas_idArea` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idArea`
    FOREIGN KEY (`areas_idArea`)
    REFERENCES `parque`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEspecie`
    FOREIGN KEY (`especies_idEspecie`)
    REFERENCES `parque`.`Especie` (`id_especie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idEspecie_idx` ON `parque`.`Especie_Areas` (`especies_idEspecie` ASC);

CREATE INDEX `idArea` ON `parque`.`Especie_Areas` (`areas_idArea` ASC);


-- -----------------------------------------------------
-- Table `parque`.`Contratado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Contratado` (
  `id_contratado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tel_fijo` VARCHAR(9) NOT NULL,
  `tel_movil` VARCHAR(9) NOT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contratado`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idContratado_UNIQUE` ON `parque`.`Contratado` (`id_contratado` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `contratado` VALUES (1,'Raul','González Escribano','916438765','654678765','Vigilante'),(2,'Victoria','Jiménez Sánchez','913653487','643986754','Cuidadora'),(3,'Fernando','Álvarez Toledo','934572837','659345968','Vigilante');
