-- MySQL Script generated by MySQL Workbench
-- 03/21/16 20:14:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parque
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parque` ;

-- -----------------------------------------------------
-- Schema parque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parque` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `parque` ;

-- -----------------------------------------------------
-- Table `parque`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Especie` (
  `id_especie` INT NOT NULL,
  `nombre_cientifico` VARCHAR(45) NOT NULL,
  `nombre_comun` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especie`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_especie_UNIQUE` ON `parque`.`Especie` (`id_especie` ASC);


-- -----------------------------------------------------
-- Table `parque`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Area` (
  `id_area` INT NOT NULL,
  `nombre_area` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idArea_UNIQUE` ON `parque`.`Area` (`id_area` ASC);


-- -----------------------------------------------------
-- Table `parque`.`EspecieArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`EspecieArea` (
  `id_especie_area` INT NOT NULL,
  `id_especie` INT NOT NULL,
  `id_area` INT NOT NULL,
  PRIMARY KEY (`id_especie_area`),
  CONSTRAINT `idArea`
    FOREIGN KEY (`id_especie`)
    REFERENCES `parque`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEspecie`
    FOREIGN KEY (`id_area`)
    REFERENCES `parque`.`Especie` (`id_especie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEspecieArea_UNIQUE` ON `parque`.`EspecieArea` (`id_especie_area` ASC);

CREATE INDEX `idArea_idx` ON `parque`.`EspecieArea` (`id_especie` ASC);

CREATE INDEX `idEspecie_idx` ON `parque`.`EspecieArea` (`id_area` ASC);


-- -----------------------------------------------------
-- Table `parque`.`Contratado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parque`.`Contratado` (
  `id_contratado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tel_fijo` VARCHAR(9) NOT NULL,
  `tel_movil` VARCHAR(9) NOT NULL,
  `tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`id_contratado`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idContratado_UNIQUE` ON `parque`.`Contratado` (`id_contratado` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
